# Generated by Django 4.1.5 on 2023-09-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='ascent',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='average_cadence',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='average_hr',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='calories',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='descent',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='fat_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='running_index',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='training_load',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
