# Generated by Django 4.1.5 on 2023-09-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trainingdata_ascent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='average_cadence',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='running_index',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
