# Generated by Django 4.1.5 on 2023-09-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trainingdata_average_cadence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
